name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04  # explicitly using ubuntu-22.04 for stability
    steps:
      - uses: actions/checkout@v2
      - uses: Borales/actions-yarn@v2.3.0
        with: 
          cmd: install
      - uses: Borales/actions-yarn@v2.3.0
        with: 
          cmd: build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build


